# Site settings
title: Christopher Murphy - Blog
tagline: "Exploring front-end development and design."
email: christopherianmurphy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog of Christopher Murphy, front-end developer and designer.
baseurl: "" # the subpath of your site, e.g. /blog. This needs to be set to "" at build-time. Set to "./" to preview local build.
url: "http://blog.christopherianmurphy.com" # the base hostname & protocol for your site
twitter_username: splode
github_username:  splode

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
plugins:
- jekyll-paginate
# - octopress-minify-html
- jekyll-minifier
- jekyll-sitemap
- emoji_for_jekyll
paginate: 7
paginate_path: 'blog/page:num'
permalink: /:year/:month/:title.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
