# Site settings
title: Christopher Murphy - Blog
email: christopherianmurphy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog of Christopher Murphy, front-end designer and developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.christopherianmurphy.com" # the base hostname & protocol for your site
twitter_username: splode
github_username:  splode

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
gems: 
 - jekyll-paginate
 - octopress-autoprefixer
paginate: 6
paginate_path: 'blog/page:num'
permalink: /blog/:title